### PR TITLE
Add DropdownCustom component

### PR DESCRIPTION
**Pull request by henckellbach**
I decided to create a new dropdown component using custom designed options instead of the browser native `<option>`.
As the styles and logic differ quite a lot, I opted to make this a new component and not unify with the existing Dropdown.

Any feedback welcome 💪 

New component
image

Actual OS
image

---

## Possible Next Steps
- better test coverage?
- Storybook controls, actions?
- rename `Dropdown` to `Select` and `DropdownCustom` to `Dropdown`?
- utilize `PropsWithHTMLAttributes` across the codebase?

### CODE REVIEW

**Comment by ggdaltoso** [comment]
There is two new commits in your branch fixing all building issues and we are ready to review it and discuss this new component!

**Comment by henckellbach** [comment]
@ggdaltoso Awesome! This is my first contribution to this project so please feel free to point out any issues 🙂

**Comment by ggdaltoso** [comment]
Hey, @henckellbach!

Is it still interesting to you?

**Comment by ggdaltoso** [comment]
Closing this one due to inactivity. Just a reminder, we can always come back to it if we need it. 🪐

**Pull request closed without merging**
