### PR TITLE
added new icons

### PR DESCRIPTION
**Pull request by accuvit**
I have extracted every icon from the windows 95 files, and added what I found the most useful to the project. If anyone want the rest of the icos just PM me! :3

### CODE REVIEW

**Comment by ggdaltoso** [comment]
What an amazing contribution you made!

You've added a lot of icons! Thank you for that!

I will approve your PR but I need you to change the commit message. It must begin with `feat: `. The project follows the [conventional changelog](https://github.com/conventional-changelog/conventional-changelog), used by
[semantic-release](https://github.com/semantic-release/semantic-release) to automatically generate and publish new versions of React95 to NPM.

I would suggest you:
 - run `git commit --amend` or
 - rollback your last commit using `git reset HEAD~1` and run `npm run commit`. The prompt will ask some questions and you just need to follow the steps provided by [commitizen](https://github.com/commitizen/cz-cli).

**Comment by accuvit** [comment]
@ggdaltoso done! I just used the amend method

**Comment by ggdaltoso** [comment]
@all-contributors please add @accuvit for code

**Pull request merged**
