### PR TITLE
chore: remove unused dependencies and shift non-runtime deps to devDependencies

### LINKED ISSUE #242: Remove unnecessary dependencies and move dev dependencies to devDependencies
Some dependencies like `styled-system/prop-types`, `react-virtualized`, `isomorphic-fetch` and `@types/react-virtualized` don't appear to be used in the project and could be removed.

Others, like `ts-loader`, `icojs` are only used in development of React95 and can be moved to `devDependencies` to make sure consuming apps don't end up with those packages in their `node_modules` when they install React95.

If we tidy these up, it can simplify `node_modules` for users a bit

### PR DESCRIPTION
**Pull request by kirkobyte**
Removes any unused dependencies and move non-runtime dependencies to devDependencies

fixes: #242

### CODE REVIEW

**Comment by ggdaltoso** [comment]
Thanks for the cleaning! 🚀

**Comment by ggdaltoso** [comment]
I'm getting an error when I run `yarn tests`.

```bash

 FAIL   clippy  packages/clippy/tests/useClippy.test.js
  ● Test suite failed to run

    Cannot find module 'react-test-renderer' from 'pure.js'

    Require stack:
      /Users/ggdaltoso/Workspace/private/React95/node_modules/@testing-library/react-hooks/lib/pure.js
      /Users/ggdaltoso/Workspace/private/React95/node_modules/@testing-library/react-hooks/lib/index.js
      /Users/ggdaltoso/Workspace/private/React95/packages/clippy/tests/useClippy.test.js

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (../../node_modules/@testing-library/react-hooks/lib/pure.js:38:26)
```

[ref](https://github.com/testing-library/react-hooks-testing-library#peer-dependencies)

**Comment by kirkobyte** [comment]
Ah sorry, I'd assumed that the tests would be run in CI! I've popped `react-test-renderer` back for clippy

**Comment by ggdaltoso** [comment]
> Ah sorry, I'd assumed that the tests would be run in CI! I've popped `react-test-renderer` back for clippy

It ~~should~~ run on every [`push`](https://github.com/React95/React95/blob/master/package.json#L72)

Everything seems to be working now!

**Review by ggdaltoso — APPROVED** [review]

**Comment by kirkobyte** [comment]
Oh right! The husky hooks don't seem to be getting triggered on my machine

**Pull request merged**
