### PR TITLE
docs: added my website to README - Michal

### PR DESCRIPTION
**Pull request by cheatingthemichal**

### CODE REVIEW

**Review by ggdaltoso — COMMENTED** [review]
Hi, @cheatingthemichal, and thanks for using React95!

You have an amazing website! 

It is an honor to add your site to our README but, following [our contributing guidelines](https://github.com/React95/React95/blob/master/CONTRIBUTING.md#file-structure), I'd like to ask you to revisit your commit and prepend the message with `docs:`:
 - `docs: added my website to README - Michal`

This is important because our CI will look at it for versioning our library.
I hope you understand 🕊️

**Comment by cheatingthemichal** [comment]
Thanks! I think I updated the commit.

**Review by ggdaltoso — APPROVED** [review]
Great portfolio, @cheatingthemichal!

**Comment by ggdaltoso** [comment]
@all-contributors please add @cheatingthemichal for doc

**Pull request merged**
