### PR TITLE
Add more win95 icons

### PR DESCRIPTION
**Pull request by oddisland**
I just simply added a part of the win95 icons :)

### CODE REVIEW

**Comment by allyssonsantos** [comment]
Hi @oddisland!

Thanks for the icons!
I have a question, why did you delete the `package-lock.json`?

**Comment by oddisland** [comment]
Hi @allyssonsantos 

Sry, it's my fault .
That should not be deleted!

**Comment by allyssonsantos** [comment]
> Hi @allyssonsantos
> 
> Sry, it's my fault .
> That should not be deleted!

@oddisland Could you add the file in a new commit?

**Comment by oddisland** [comment]
@allyssonsantos No problem.

**Pull request closed without merging**
