### PR TITLE
Fix styles for Checkbox

### LINKED ISSUE #129: Checkboxes don't pass styles through
If I try to render a checkbox in the following way:

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Checkbox } from "@react95/core";

let style = {
    left: "200px",
    top: "200px",
    position: "relative"
};

ReactDOM.render(
    <div>
        <Checkbox style={style} />
    </div>,
    document.getElementById("app"),
);
```

relative positioning isn't respected. In contrast, using `Button`, styles are preserved.

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Button } from "@react95/core";

let style = {
    left: "200px",
    top: "200px",
    position: "relative"
};

ReactDOM.render(
    <div>
        <Button style={style} />
    </div>,
    document.getElementById("app"),
);
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #129

### CODE REVIEW

**Comment by ggdaltoso** [comment]
Awesome PR, @DanielRosenwasser !!!

Glad to see you've added the unit test covering this!

An important note here is that we need the commit messages to follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) pattern to build and publish React95 automatically. 

Could you, please, revisit your commits and make those changes?

If I may suggest to you:
1. revert your commit, run `yarn run commit`, and follow the instructions in CLI (recommended).
2. edit your commit messages with `git commit --amend`.

**Comment by DanielRosenwasser** [comment]
Sure thing, fixed up the commit messages. Let me know if this works!

**Comment by DanielRosenwasser** [comment]
Okay, now I actually used `yarn run commit`.

**Comment by ggdaltoso** [comment]
@all-contributors please add @DanielRosenwasser for bug, doc, code, test

**Pull request merged**
