### PR TITLE
✨ Create new Avatar Component

### PR DESCRIPTION
**Pull request by mmartinsolliv**
# ✨ Add Avatar

Avatar default:
image

Avatar with Circle:
image

Avatar with Letters:
image

The component has the following props:
- size
- circle

## Changes

- create new component `<Avatar />`
- add snapshot
- add stories

### CODE REVIEW

**Comment by ggdaltoso** [comment]
Did some code changes to make the border more like what we have in React95

image

but, anyway, thanks for your contribution, @mmartinsolliv !!

As soon as you could check the diff I did, let me know

**Comment by mmartinsolliv** [comment]
It was excellent, @ggdaltoso! Thank you for your help 🚀  ❤️

**Comment by ggdaltoso** [comment]
@all-contributors please add @mmartinsolliv for code and ideas

**Comment by ggdaltoso** [comment]
@all-contributors please add @mmartinsolliv for code, ideas, and financial

**Pull request merged**
