### PR TITLE
Alert fix

### PR DESCRIPTION
**Pull request by belakm**
When used with next.js, the SSR side of Next would throw an error that `window is undefined` because server does not know about window when it wants to pre-render.

I added an undefined check that remedies this problem.

### CODE REVIEW

**Review by ggdaltoso — COMMENTED** [review]
Hi, @belakm !

Glad to see you are using 95 in a NextJS project! I've never tried on that!
Besides this issue you had, how is the experience going?

We also have some `window` usage like at [Tooltip](https://github.com/React95/React95/blob/master/packages/core/components/Tooltip/Tooltip.tsx#L42). Could you, please, check it too?

**Comment by kaiofelipejs** [comment]
Good PR! 
I have the same issue using Gatsby

**Comment by belakm** [comment]
@ggdaltoso

Hey, yeah i love this project! <3

Otherwise the project is OK for next.js, as the problem only occurs at compile on the server, the `windows` is safe as long as it is used inside lifecycle hooks or events.

> Besides this issue you had, how is the experience going?

Very nice, its a beautiful library with many great elements, i'm happy to have found it

**Review by allyssonsantos — APPROVED** [review]

**Review by ggdaltoso — APPROVED** [review]

**Comment by ggdaltoso** [comment]
@all-contributors please add @belakm for bug, code

**Pull request merged**
