### PR TITLE
chore(icons): tidy up old png files

### PR DESCRIPTION
**Pull request by kirkobyte**
The PNG files that were previously used by the icons package are no longer needed now that they're
generated on the fly from the source .ico files

### CODE REVIEW

**Comment by kirkobyte** [comment]
It's much nicer having this as a separate PR 😂

**Comment by ggdaltoso** [comment]
Indeed! 

We just need to make sure that @react95/icons README will still work. Maybe we can change from `PNG` to the original `ico` extension.

What do you think?

**Comment by kirkobyte** [comment]
Ah yeah, good point! I've just pushed that change. I added a line up the top of the file that specifies some additional size variants are available in Storybook too. Do you think that makes sense?

**Comment by kirkobyte** [comment]
Oh, I see the README already only had one size of each icon, so maybe that's not required?

**Comment by ggdaltoso** [comment]
> Oh, I see the README already only had one size of each icon, so maybe that's not required?

Don't worry. It's not mandatory.

> Ah yeah, good point! I've just pushed that change. I added a line up the top of the file that specifies some additional size variants are available in Storybook too. Do you think that makes sense?

Great! Good catch!

**Comment by ggdaltoso** [comment]
@all-contributors please add @kirkobyte for doc and ideas

**Pull request merged**
